### ISSUE TITLE
fix unsafe

### ISSUE THREAD

**Issue by zoosky** [forgerpl/webcrawl#1]
https://github.com/zoosky/webcrawl/blob/afc2612fd1eec3c0a00393a9c015de783beb2850/crawler/src/fetcher.rs#L11-L11

**Comment by forgerpl** [comment]
This is not an unsafe call, in case when the underlying buffer doesn't contain a valid utf-8 string it will panic.
There could be some other means of dealing with invalid data, but it would require introducing proper failure handling. One of other options is to use something like [String::from_utf8_lossy](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy)
